### ISSUE TITLE
Not finding an rhx_gis key in window._sharedData

### ISSUE THREAD

**Issue by grrttweaver** [Snbig/InstaTrack#1]
Traceback (most recent call last):
  File "InstaTracker.py", line 45, in <module>
    print(useridToUsername("<<ID>>"))
  File "InstaTracker.py", line 24, in useridToUsername
    rhx_gis = json.loads(re.compile('window._sharedData = ({.*?});', re.DOTALL).search(r1).group(1))['rhx_gis']
KeyError: 'rhx_gis'

**Comment by Snbig** [comment]
About three days ago Instagram changed its GraphQL API implementation so Instatrack does not work anymore.
I do my best to patch it soon.

**Comment by grrttweaver** [comment]
Just letting you know! Thanks!
