### ISSUE TITLE
#Fixed:::UserID to UserName doesn’t work anymore - will You fix it anytime soon?

### ISSUE THREAD

**Issue by github-userx** [Snbig/InstaTrack#2]
Thanks so much for creating this tool!

**Comment by Snbig** [comment]
You're welcome ❤
Code has been fixed before in https://github.com/Snbig/InstaTrack/commit/5da63c59397328750225754d768da1389915f155 commit.

**Comment by github-userx** [comment]
@Snbig bless you. Many many thanks.

Currently I have it that I can execute

   python3 usernameToUserID.py 

And it will ask/ prompt for a username to input.

But with the userIDtoUsername I always have change the UserID in the python file itself (in line 46):

print(useridToUsername("00000000"))

Do You think it’s possible for the userIDtoUsername script to ask for userID input?

Best Regards!

**Comment by github-userx** [comment]
i assume theoretically we could also have a single app with parameters like:

#get userID from username
   instatrack -id justintimberlake

#get username from userID
    instatrack -u 1234567812345

But honestly I am also absolutely fine with two .py files that do work flawlessly!

<3

**Comment by Snbig** [comment]
**Command line options added to code** https://github.com/Snbig/InstaTrack/commit/2e11349addb090249483e05ca4b5563efb11bdb5
_Gook Luck_ 😉

**Comment by github-userx** [comment]
You‘re the best!,! ;) incredible!

**Comment by github-userx** [comment]
@Snbig I am getting syntax error.

   python3 InstaTrack.py -id justinbieber
   File "InstaTrack.py", line 64
   print(f"[+] Username: {username}")
   ^
    SyntaxError: invalid syntax

**Comment by Snbig** [comment]
- _First of all clone the latest commit._

- _Use "-u/--user" instead of "-i/--id" to lookup UserID._
- _Also Check help_ [-h/--help]:
`$ python3 InstaTracker.py -u justinbieber`
`[+] UserID: 6860189`

**Comment by github-userx** [comment]
I get the same error when using -u justinbieber and using the latest commit.

Using Python3.5.3

**Comment by github-userx** [comment]
Do you use Python3.6?

**Comment by Snbig** [comment]
Yes.
# F-strings is not available for python before 3.6. #
To make it compatible for python before 3.6 replace f-strings with string formatting.
`"[+] Username: {}".format(username)`
`"[+] UserID: {}".format(userid)`

**Comment by github-userx** [comment]
Thanks, that made it work.



2. Juni 2019, 11:19 from notifications@github.com:
