### ISSUE TITLE
[Enchancment] Ability to pass a .txt file

### ISSUE THREAD

**Issue by ghost** [Snbig/InstaTrack#3]
Hi,
Could you add an argument so it would be possible to pass a .txt file containing id numbers of instagram users (one in each line) ? 
The script would produce a .txt of usernames

**Comment by rabe398** [comment]
And please add a timeout between each api call

**Comment by Snbig** [comment]
> Hi,
> Could you add an argument so it would be possible to pass a .txt file containing id numbers of instagram users (one in each line) ?
> The script would produce a .txt of usernames

Thank you for your suggestion ❤

List lookup add to code https://github.com/Snbig/InstaTrack/commit/3cc98829657fada307e6e46cdd1f563a2c4204d7

**Comment by Snbig** [comment]
> And please add a timeout between each api call

Is there any limitation on Instagram API call?
I don't understand why you need to set timeout for api call.

**Comment by github-userx** [comment]
@Snbig you’re the best for all these updates!! <3

**Comment by rabe398** [comment]
@Snbig Yep, there’s a limit on instagrap api calls, and I’m not sure what is it.
You can try to call some functions 2000 times without timeout, and you will get a messege from instagram “ an error occured please try again later”

**Comment by rabe398** [comment]
The script crashed on second run.
I though I would test what would happen if you enter a some active user ids in .txt file and mix those with a user id of temporarily deactivate account. 
Here's my input.txt:
8163012263
11216025632

command used:
python InstaTracker.py -f input.txt

output:
C:\Users\Test\Desktop>python InstaTracker.py -f input.txt
Traceback (most recent call last):
  File "InstaTracker.py", line 112, in <module>
    main()
  File "InstaTracker.py", line 75, in main
    username = useridToUsername(e)
  File "InstaTracker.py", line 45, in useridToUsername
    username = json.loads(r3)['data']['user']['reel']['user']['username']
TypeError: 'NoneType' object is not subscriptable

**Comment by rabe398** [comment]
@Snbig any idea why it crashed?
