### ISSUE TITLE
[Enhancement] Export as Excel

### ISSUE THREAD

**Issue by Snbig** [Snbig/InstaTrack#6]
Could add another option to export the results as an excel file? First coloumn with user id, and second one with the username

_Originally posted by @rabe398 in https://github.com/Snbig/InstaTrack/issues/3#issuecomment-506551291_

**Comment by Snbig** [comment]
I wrote gist to export "results.txt" to Excel format (xls)
Gist : https://gist.github.com/Snbig/50b33b355b9c53268871e8dc44b03b70

**Comment by rabe398** [comment]
Thanks for your hard work.
