### ISSUE TITLE
Is ID to username broken again?

### ISSUE THREAD

**Issue by darthclide** [Snbig/InstaTrack#8]
python InstaTracker.py -i 534895514

comes back with

File "InstaTracker.py", line 138, in <module>
    main()
  File "InstaTracker.py", line 121, in main
    username = useridToUsername(args.id)
  File "InstaTracker.py", line 58, in useridToUsername
    checkTokens()
  File "InstaTracker.py", line 18, in checkTokens
    getTokens()
  File "InstaTracker.py", line 28, in getTokens
    query_hash = re.findall(r'{value:!0}\);const o=\"(.*?)\"', r)[0]

**Comment by heitorsampaio** [comment]
Yeah, i think so, i have the same problem here

**Comment by Snbig** [comment]
**Thank you for your notifications.**
**The problem Fixed by** https://github.com/Snbig/InstaTrack/commit/43d83c77130a24ee9e59c59736ce98b49aaaa7ec **commit.**

**Comment by darthclide** [comment]
Awesome. Works fine now. May I ask why you think they changed it? (just curious)

**Comment by Snbig** [comment]
> Awesome. Works fine now. May I ask why you think they changed it? (just curious)

Sometimes they change the query_hash variable. So to extract its value we have to update the regex which indicates to new variable.

**Comment by darthclide** [comment]
Hmm, I guess I was hoping you could guess "why" they change it. Security I guess?

**Comment by Tinchox17** [comment]
is broken again.
